### ISSUE TITLE
请问如何让Calibre支持书籍评论呢？

### ISSUE THREAD

**Issue by ctrol** [talebook/calibre-webserver#11]
最近准备把这个发布到网上，希望能够集成书籍评论系统，请问有没有办法集成呢？只需要简单的评论就行。

**Comment by talebook** [comment]
之前使用过搜狐畅言的评论功能，目前已注释掉。如有需要你可以自行开启。

https://github.com/talebook/calibre-webserver/blob/master/webserver/templates/book/detail.html#L157

**Comment by ctrol** [comment]
感谢！已经看到了
