### ISSUE TITLE
请问这个Calibre是否支持同一书名，上传多个版本、多个格式（epub、mobi、PDF、awz）的书籍？

### ISSUE THREAD

**Issue by ctrol** [talebook/calibre-webserver#12]
请问这个Calibre是否支持同一书名，上传多个版本、多个格式（epub、mobi、PDF、awz）的书籍？同时对每一个版本允许用户做简单的评论，比如反馈清晰度，可读性，对书籍的见解等评论？

**Comment by talebook** [comment]
之前使用过搜狐畅言的评论功能，目前已注释掉。如有需要你可以自行开启。

https://github.com/talebook/calibre-webserver/blob/master/webserver/templates/book/detail.html#L157

**Comment by talebook** [comment]
PS：不支持同一书名上传多个版本。原因是为了减少存储空间。

**Comment by cute-angelia** [comment]
不合理啊。 还是要支持上传多个格式
