### ISSUE TITLE
请问如何设置让web短支持SSL？

### ISSUE THREAD

**Issue by ctrol** [talebook/calibre-webserver#13]
请问如何设置让web短支持SSL？自行添加端口，总是不行，我已经申请了Let's Encrypted的SSL证书

**Comment by talebook** [comment]
https://github.com/talebook/calibre-webserver/blob/master/conf/nginx/talebook.org

**Comment by talebook** [comment]
请参考这份nginx配置：https://github.com/talebook/calibre-webserver/blob/master/conf/nginx/talebook.org

**Comment by ctrol** [comment]
感谢，正在查看。
