### ISSUE TITLE
请问一下，https://www.talebook.org怎么查找图书

### ISSUE THREAD

**Issue by joln** [talebook/calibre-webserver#14]
请问一下，https://www.talebook.org怎么查找图书，目前只能看到默认的书，另外为什么用git clone https://github.com/talebook/talebook-library.git /data/books/library 大概只有1500本左右的样子，具体有多少本书？

**Comment by talebook** [comment]
talebook-library 里的书库应该有几千本吧，具体我也没数过。

www.talebook.org因为某些不可说的原因关闭了。
