### ISSUE TITLE
请教一下如何开启多用户登录

### ISSUE THREAD

**Issue by a87750530** [talebook/calibre-webserver#16]
难道微博、QQ、git上的全部都要设置才能开启，多用户登录？
请教一下如何开启多用户登录，能不能出一个集成自己的用户系统呢，
目前docker版本，结果想开启多用户登录，结果500: Internal Server Error

**Comment by talebook** [comment]
设置任意一个第三方登录即可。例如只开启QQ登录就OK。

本地用户管理，这个是在后续的版本才会开发支持，预计年底吧。

报错的解释可以查看另一个issue： https://github.com/talebook/calibre-webserver/issues/15
