### ISSUE TITLE
docker安装后，初始设置网页无法完成设置

### ISSUE THREAD

**Issue by Refarin** [talebook/calibre-webserver#22]
最新版，初始设置网页点击完成设置，就会出现“服务器故障！请稍候刷新页面重试！”

**Comment by bimzcy** [comment]
请再更新至最新版，此问题已经解决

**Comment by bimzcy** [comment]
> 最新版，初始设置网页点击完成设置，就会出现“服务器故障！请稍候刷新页面重试！”

请再更新至最新版，此问题已经解决

**Comment by Refarin** [comment]
> > 最新版，初始设置网页点击完成设置，就会出现“服务器故障！请稍候刷新页面重试！”
> 
> 请再更新至最新版，此问题已经解决

更新最新版，还是同样情况依然报错

**Comment by talebook** [comment]
请提供log目录下的calibre-webserver.log，然后才好排查问题。

**Comment by Refarin** [comment]
> 请提供log目录下的calibre-webserver.log，然后才好排查问题。

能问下Docker安装的log是在哪个目录下吗？

**Comment by talebook** [comment]
就是挂载的路径里有个log文件夹
docker内部的话，完整文件路径是：
/data/log/calibre-webserver.log

**Comment by bimzcy** [comment]
> > > 最新版，初始设置网页点击完成设置，就会出现“服务器故障！请稍候刷新页面重试！”
> > 
> > 
> > 请再更新至最新版，此问题已经解决
> 
> 更新最新版，还是同样情况依然报错

在我和你回复的空隙之间，作者又更新了一个最新版，这个最新版确实有这个错误

**Comment by talebook** [comment]
请注意：
挂在的路径为 /data ，请检查是否挂在错误路径了。

中途某个版本调整了路径，后面都修正回 /data 了，请升级到最新的latest版本再试试。

**Comment by Refarin** [comment]
> 请注意：
> 挂在的路径为 /data ，请检查是否挂在错误路径了。
> 
> 中途某个版本调整了路径，后面都修正回 /data 了，请升级到最新的latest版本再试试。

之前看说明，挂载在/data/books，回去再试下
