### ISSUE TITLE
希望能调高上传文件大小

### ISSUE THREAD

**Issue by bimzcy** [talebook/calibre-webserver#23]
现在上传文件大小被限制在了20MB，这个上限特~别~不~够~用！希望能调高文件大小上限，或是允许自定义上限。我的群晖内存有32GB，所以不在意多占用一些内存。

**Comment by talebook** [comment]
https://github.com/talebook/calibre-webserver/blob/develop/document/INSTALL.zh_CN.md#%E4%B8%8A%E4%BC%A0%E6%96%87%E4%BB%B6%E7%9A%84%E5%A4%A7%E5%B0%8F
