### ISSUE TITLE
QQ，微博，github登录404，下载文件404，api文件缺失

### ISSUE THREAD

**Issue by a87750530** [talebook/calibre-webserver#26]
QQ、微博、github登录404，应该是api文件缺失
api/login/qq
404: Not Found
api/login/github
404: Not Found
api/login/weibo
404: Not Found
书籍上传后下载404
api/book/4488.AZW3
403: Forbidden
基本确定是api文件缺失

**Comment by talebook** [comment]
404问题已修复

**Comment by rainsuns** [comment]
借楼问下，QQ、微博登陆的回调地址要怎么填？

**Comment by talebook** [comment]
> 借楼问下，QQ、微博登陆的回调地址要怎么填？

手动配置可以参考这个文档。
https://github.com/talebook/calibre-webserver/blob/master/document/INSTALL.zh_CN.md#%E7%94%B3%E8%AF%B7%E7%A4%BE%E4%BA%A4%E7%BD%91%E7%AB%99%E5%BA%94%E7%94%A8%E8%B4%A6%E5%8F%B7%E5%A4%9A%E7%94%A8%E6%88%B7%E4%BD%BF%E7%94%A8

UI也可以直接修改，在【头像】-【管理员入口】-【社交网络登录】里

**Comment by rainsuns** [comment]
> > 借楼问下，QQ、微博登陆的回调地址要怎么填？
> 
> 手动配置可以参考这个文档。
> https://github.com/talebook/calibre-webserver/blob/master/document/INSTALL.zh_CN.md#%E7%94%B3%E8%AF%B7%E7%A4%BE%E4%BA%A4%E7%BD%91%E7%AB%99%E5%BA%94%E7%94%A8%E8%B4%A6%E5%8F%B7%E5%A4%9A%E7%94%A8%E6%88%B7%E4%BD%BF%E7%94%A8
> 
> UI也可以直接修改，在【头像】-【管理员入口】-【社交网络登录】里
KEY和SECRET都有了，但是QQ、微博那边要填个回调地址，没找到这个地址，Github的回调地址在oldiy的blog那找到了。

**Comment by talebook** [comment]
> > > 借楼问下，QQ、微博登陆的回调地址要怎么填？
> > 
> > 
> > 手动配置可以参考这个文档。
> > https://github.com/talebook/calibre-webserver/blob/master/document/INSTALL.zh_CN.md#%E7%94%B3%E8%AF%B7%E7%A4%BE%E4%BA%A4%E7%BD%91%E7%AB%99%E5%BA%94%E7%94%A8%E8%B4%A6%E5%8F%B7%E5%A4%9A%E7%94%A8%E6%88%B7%E4%BD%BF%E7%94%A8
> > UI也可以直接修改，在【头像】-【管理员入口】-【社交网络登录】里
> > KEY和SECRET都有了，但是QQ、微博那边要填个回调地址，没找到这个地址，Github的回调地址在oldiy的blog那找到了。

https://wenyuange.org/auth/complete/github.do

**Comment by talebook** [comment]
> > > 借楼问下，QQ、微博登陆的回调地址要怎么填？
> > 
> > 
> > 手动配置可以参考这个文档。
> > https://github.com/talebook/calibre-webserver/blob/master/document/INSTALL.zh_CN.md#%E7%94%B3%E8%AF%B7%E7%A4%BE%E4%BA%A4%E7%BD%91%E7%AB%99%E5%BA%94%E7%94%A8%E8%B4%A6%E5%8F%B7%E5%A4%9A%E7%94%A8%E6%88%B7%E4%BD%BF%E7%94%A8
> > UI也可以直接修改，在【头像】-【管理员入口】-【社交网络登录】里
> > KEY和SECRET都有了，但是QQ、微博那边要填个回调地址，没找到这个地址，Github的回调地址在oldiy的blog那找到了。

类似：
https://talebook.org/auth/complete/qq.do
https://talebook.org/auth/complete/weibo.do
