### ISSUE TITLE
docker版本安装之后，使用宝塔面板反代并部署ssl，在线阅读功能失效

### ISSUE THREAD

**Issue by chaosye0** [talebook/calibre-webserver#39]
如题，docker版本安装之后，使用宝塔面板反向代理并部署ssl，开启https时在线阅读功能失效，阅读页面加载不出来。如图
![QQ截图20200519192548](https://user-images.githubusercontent.com/30192801/82320913-a1028680-9a06-11ea-9c8c-369d16254c42.jpg)

**Comment by talebook** [comment]
你部署了SSL？ 该问题看起来像是在 https 页面下引用了 http 资源，导致浏览器拒绝访问。

配置SSL时，请注意设置X-Scheme头部，把https/http信息带给服务器，例如下面这个是NGINX的配置：

```
    location / {
        proxy_pass       http://127.0.0.1:8000;
        proxy_set_header Host      $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme  $scheme;
        proxy_redirect   off;
    }
```
