### ISSUE TITLE
推送一直不成功,在邮箱里有显示已发送?

### ISSUE THREAD

**Issue by shelken** [talebook/calibre-webserver#40]
不知道为什么,在邮箱有看到已经发送的内容,但是 kindle 一直刷不出来,自己试着用相同的一封邮件在手机端发送一次,竟然很快同步上,不知道是不是邮箱推送的问题?(另外,就是原格式不是 mobi,他显示在转换,然后一直都是在转换,虽然邮箱已经看到了,应该是 bug,还有转换过的也会一直显示在推送,没有出现过推送成功的提示)
![jpg](https://tva1.sinaimg.cn/large/007S8ZIlgy1gfjou7cvwlj30ri09nwee.jpg)
![2](https://tva1.sinaimg.cn/large/007S8ZIlgy1gfjp0gr75nj30r609qq2v.jpg)

**Comment by talebook** [comment]
1、如果是邮箱配置问题，可以在管理员入口的邮件服务配置中，点击【测试邮件】验证下。
2、如果是mobi转换格式的问题（例如有可能转换失败），那么需要去查看下日志了 ( log/calibre-webserver.log）才能明白是什么问题
