### ISSUE TITLE
手动安装是否少了前端编译步骤？

### ISSUE THREAD

**Issue by lixplor** [talebook/calibre-webserver#43]
手动安装后在`/var/www/calibre-webserver/webserver/settings.py`中设置了`../app/dist`。
这看起来是个vue前端，应该先`npm install --save`然后`npm run build`才会有这个目录吧？

**Comment by talebook** [comment]
https://github.com/talebook/calibre-webserver/blob/master/Dockerfile

**Comment by talebook** [comment]
https://github.com/talebook/calibre-webserver/blob/master/Dockerfile

手动安装，亦可以参考DOCKER的执行过程。

的确是需要先安装npm，并编译，才会有app/dist目录出现。
