### ISSUE TITLE
Https的端口时啥？

### ISSUE THREAD

**Issue by F7s** [talebook/calibre-webserver#44]
如题

**Comment by dickeny** [comment]
docker的镜像中没有配置https （因为没有证书）

**Comment by dickeny** [comment]
一个NGINX的HTTPS配置供参考：

upstream tornado {
    server 127.0.0.1:8000;
}

server {
    listen 80;
    server_name demo.com www.demo.com;
    return 301 https://demo.com$request_uri;
}

server {
    listen 443 ssl;
    server_name demo.com

    ssl on;
    ssl_certificate     ssl/demo.com.crt;
    ssl_certificate_key ssl/demo.com.key;
    
    client_max_body_size 20m;
    
    index index.php index.html index.htm;
    root /data/www/demo.com/htdocs/;
    


    location / {
        proxy_pass       http://tornado;
        proxy_set_header Host      $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme  $scheme;
        proxy_redirect   off;
    }
}

**Comment by talebook** [comment]
docker的镜像中没有配置https （因为没有证书）。一个NGINX的HTTPS配置，供你参考：

upstream tornado {
    server 127.0.0.1:8000;
}

server {
    listen 80;
    server_name demo.com www.demo.com;
    return 301 https://demo.com$request_uri;
}

server {
    listen 443 ssl;
    server_name demo.com

    ssl on;
    ssl_certificate     ssl/demo.com.crt;
    ssl_certificate_key ssl/demo.com.key;
    
    client_max_body_size 20m;
    
    index index.php index.html index.htm;
    root /data/www/demo.com/htdocs/;
    
    location / {
        proxy_pass       http://tornado;
        proxy_set_header Host      $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme  $scheme;
        proxy_redirect   off;
    }
}

**Comment by leomanxin** [comment]
你好，请问具体应该如何设置

**Comment by talebook** [comment]
> 你好，请问具体应该如何设置


配置https的话，推荐的方案是搭建一个nginx服务器，使用如下的配置。其中，
1，talebook程序运行监听8000端口；
2，https访问的域名是`demo.com`；
3，证书和私钥保存到`/etc/nginx/ssl/`目录中；
4，下面的配置添加到`/etc/nginx/nginx.conf`中；

```
upstream tornado {
server 127.0.0.1:8000;
}

server {
listen 80;
server_name demo.com www.demo.com;
return 301 https://demo.com$request_uri;
}

server {
listen 443 ssl;
server_name demo.com

ssl on;
ssl_certificate     ssl/demo.com.crt;
ssl_certificate_key ssl/demo.com.key;

client_max_body_size 20m;

index index.php index.html index.htm;
root /data/www/demo.com/htdocs/;

location / {
    proxy_pass       http://tornado;
    proxy_set_header Host      $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme  $scheme;
    proxy_redirect   off;
}
```
