### ISSUE TITLE
demo is dead

### ISSUE THREAD

**Issue by Efreak** [talebook/calibre-webserver#49]
https is misconfigured
 - your certificate doesn't contain demo.talebook.org)
 - you only have tls 1.0, not 1.1, 1.2, or 1.3...TLS 1.0 is insecure.

See more info [here](https://www.ssllabs.com/ssltest/analyze.html?d=demo.talebook.org)

Bad gateway error on http and also on https once you find a browser that doesn't care about bad certificates (elinks works for me).

**Comment by talebook** [comment]
Thanks for your report. The demo is online again, and configure https ( but don't force http redirect https ).
