### ISSUE TITLE
希望能够支持中文文件名

### ISSUE THREAD

**Issue by czyrichard** [talebook/calibre-webserver#54]
我通过https://github.com/snomiao/calibre-utf8-path 把Calibre文件库里的文件都变成了中文文件名，方便平时搜索，但是在Calibre-Webserver里面发现中文文件名的文件都无法在线阅读了，页面会显示“500: Internal Server Error”，不知道下个版本能不能支持一下，多谢。

**Comment by talebook** [comment]
我研究下。
如果方便的话，请你提供下metadata.db文件

**Comment by czyrichard** [comment]
请参阅附件。

[metadata.zip](https://github.com/talebook/calibre-webserver/files/5420671/metadata.zip)

**Comment by talebook** [comment]
已实现
