### ISSUE TITLE
建议: 调整默认nginx上传body大小

### ISSUE THREAD

**Issue by xxxsen** [talebook/calibre-webserver#69]
目前docker版本的nginx body限制了20M, 这个地方完全可以调大一点, 大部分情况下docker拉起来calibre-webserver, 上层还是由其他nginx转发过来的, 所以限制完全可以放在上层用户自己做。

另一种方式, 可以提供env参数, 方便用户自己调整, 目前docker里面要修改这个`client_max_body_size` 还是比较麻烦的, 要登陆到容器里面, 然后把vim装上才行。

另一个建议: 增加下pdf阅读器支持。

**Comment by talebook** [comment]
已支持env参数，名称是 NGINX_CLIENT_MAX_BODY_SIZE

**Comment by talebook** [comment]
https://github.com/talebook/calibre-webserver/blob/master/document/INSTALL.zh_CN.md#%E4%B8%8A%E4%BC%A0%E6%96%87%E4%BB%B6%E7%9A%84%E5%A4%A7%E5%B0%8F
